import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#050c17" },
  scrollContent: { paddingBottom: 20 },
  header: {
    flexDirection: "row",
    justifyContent: "center",
    paddingVertical: 30,
  },
  logoText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    letterSpacing: 2,
  },
  logoIcon: { color: "#00d1ff", fontSize: 20, marginLeft: 5 },
  imageWrapper: { alignItems: "center", marginVertical: 20 },
  imageFrame: {
    borderWidth: 2,
    borderColor: "#00d1ff",
    borderRadius: 15,
    padding: 5,
  },
  profileImg: { width: 300, height: 250, borderRadius: 10 },
  content: { paddingHorizontal: 30 },
  title: { color: "#fff", fontSize: 24, fontWeight: "bold", marginBottom: 15 },
  highlight: { color: "#00d1ff" },
  description: {
    color: "#a0a0a0",
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 25,
  },
  mainButton: {
    backgroundColor: "#00d1ff",
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
    marginBottom: 10,
  },
  outlineButton: {
    borderWidth: 1,
    borderColor: "#00d1ff",
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
    marginBottom: 30,
  },
  buttonText: { color: "#050c17", fontWeight: "bold", fontSize: 16 },
  outlineButtonText: { color: "#00d1ff", fontWeight: "bold", fontSize: 16 },
  sectionTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
  },
  switchContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  switchLabel: { color: "#a0a0a0", fontSize: 14 },
  socialButton: {
    borderWidth: 1,
    borderColor: "#00d1ff",
    padding: 12,
    borderRadius: 5,
    marginBottom: 10,
    alignItems: "center",
  },
  socialText: { color: "#fff", fontWeight: "500" },
  footer: {
    backgroundColor: "#00d1ff",
    padding: 15,
    alignItems: "center",
    marginTop: 30,
  },
  footerText: { color: "#050c17", fontWeight: "bold" },
  footerSubText: { color: "#050c17", fontSize: 12 },
});
